server:
  port: 8887

github:
  client:
    id: 390fafdbb045bff12f7d
    secret: c44c58bad561ee6619b8c45cfd540f39577547e4
  redirect:
    uri: http://localhost:8887/callback
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: zxs123
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true
  mvc:
    hrow-exception-if-no-handler-found: true
  resources:
    add-mappings: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: zxs.up.newlife.mapper

